name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: trcli -y \
    -h TESETRAIL_HOST \
    --project env.PROJECT_NAME \
    --username env.TESTRAIL_USER \
    --password ${{ secrets.TESTRAIL_PASS }} \
    parse_junit \
    --title "Automated Tests Run" \
    -f junit.xml