name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Install Test rail cli
        if: always()
        run: pip3 install trcli
      - name: Upload to testrail
        if: always()
        run: |
                trcli -y \
                -h ${{ vars.TESETRAIL_HOST}} \
                --project ${{ vars.PROJECT_NAME}} \
                --username ${{ vars.TESTRAIL_USER}} \
                --password "${{ secrets.TESTRAIL_PASS }}" \
                parse_junit \
                --title "Automated Tests Run" \
                -f junit.xml