name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Install Test rail cli
        if: always()
        run: pip3 install trcli
      - run: |
            curl --location 'https://${{vars.DYNATRACE_BASE_URL}}/api/v2/events/ingest' \
            --header 'Authorization: Api-Token ${{secrets.DYNATRACE_API_KEY}}' \
            --header 'Content-Type: application/json' \
            --data '{
            "eventType": "CUSTOM_DEPLOYMENT",
            "title": "Easytravel 1.1",
            "entitySelector": "type(APPLICATION)",
            "properties": {
                "dt.event.deployment.name":"Easytravel 1.1",
                "dt.event.deployment.version": "1.1",
                "dt.event.deployment.release_stage": "production" ,
                "dt.event.deployment.release_product": "frontend",
                "dt.event.deployment.release_build_version": "123",
                "approver": "Jason Miller",
                "dt.event.deployment.ci_back_link": "https://pipelines/easytravel/123",
                "gitcommit": "e5a6baac7eb",
                "change-request": "CR-42",
                "dt.event.deployment.remediation_action_link": "https://url.com",
                "dt.event.is_rootcause_relevant": true
            }
            }'
      # - name: Upload to testrail
      #   if: always()
      #   run: |
      #           trcli -y \
      #           -h ${{ vars.TESETRAIL_HOST}} \
      #           --project ${{ vars.PROJECT_NAME}} \
      #           --username ${{ vars.TESTRAIL_USER}} \
      #           --password "${{ secrets.TESTRAIL_PASS }}" \
      #           parse_junit \
      #           --title "Automated Tests Run" \
      #           -f junit.xml
